server:
  port: 8080

management.security.enabled: false

spring.h2.console.enabled: true

logging.level.org.hibernate.SQL: debug

#logging

logging:
  level:
    3ROOT: DEBUG
    au.com.ps.opal: debug
    org.springframework.data: debug
